services:
  openvpn:
    cap_add:
     - NET_ADMIN
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openvpn
    ports:
     - "1194:1194/udp"
    restart: always
    volumes:
     - ./data/conf:/etc/openvpn
    privileged: true
